### PR TITLE
Fix when Style is kNotebook_LeftTabs

### PR DESCRIPTION
**Pull request by mtangoo**
with kNotebook_LeftTabs or kNotebook_RightTabs tabs are not shown due to wrong sizer which is always applied. This PR fixes that!

### CODE REVIEW

**Comment by eranif** [comment]
Does it work in the demo app? IIRC, it does

**Comment by mtangoo** [comment]
I tried  with my app with no fancy code

```
AppNoteBook::AppNoteBook(wxWindow *parent) : Notebook(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize,
             kNotebook_Default |
             kNotebook_AllowDnD |
             kNotebook_LeftTabs)
{

}
```

It was not working. Let me test with the demo and see.
Note: SetStyle is working correctly, only the C'tor code without call to setstyle (for obvious reason, that is the sizer is always vertical)

**Comment by mtangoo** [comment]
The Demo does not work as it is. Applying the fix works fine though

**Comment by eranif** [comment]
Just tried the demo both on Windows and Debian 8 - both are working properly...

**Comment by eranif** [comment]
OK, I see the problem now. In the demo the tab orientation is first set to TOP and changing it afterward works (it goes through `SetStyle` which updates the sizers)
If you start with a default left/right notebook then it might not work

**Pull request merged**
